apiVersion: v1
kind: Pod
metadata:
  name: postgres-voting-app
  labels:
    name: postgres-voting-app
    app: demo-app
spec:
  containers:
    - name: postgres
      image: postgres:9.4
      ports:
        - containerPort: 5432