apiVersion: v1
kind: Pod
metadata:
  name: redis-voting-app
  labels:
    name: redis-voting-app
    app: redis-voting-app-pod
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379