apiVersion: v1
kind: Pod
metadata:
  name: voting-app
  labels:
    name: vote-voting-app
    app: vote-voting-app-pod
spec:
  containers:
    - name: vote-voting-app
      image: docker/example-voting-app-vote
      ports:
        - containerPort: 80
